package com.example.Sahtech.Enum;

public enum Maladie {
    DIABETIQUE,
    OBESITE,
    HYPERTENSION,
    CHOLESTEROL,
    MALADIE_CARDIAQUE,
    INTOLERANCE_LACTOSE,
    CELIAQUIE,
    ALLERGIE_ARACHIDES,
    ALLERGIE_GLUTEN,
    ALLERGIE_FRUITS_DE_MER,
    MALADIE_RENALE,
    HEPATITE,
    ASTHME,
    MALADIE_COELIAQUE

}
