package com.example.Sahtech.Enum;

public enum Objectif {
    REDUIRE_LE_CHOLESTEROL,
    PERDRE_DU_POIDS,
    PRENDRE_DU_MUSCLE,
    AMELIORER_LA_DIGESTION,
    REDUIRE_LA_TENSION_ARTERIELLE,
    ADOPTER_UNE_ALIMENTATION_SAINE,
    EVITER_LES_PRODUITS_ALLERGENES;


}
